coverage:
  status:
    patch:
    
      main:
        target: 80%
        threshold: 1%
        
      develop:
        target: 80%
        threshold: 1%

      default:
        target: off 
        
    project:
      default:
        target: auto
        threshold: 2%

comment:
  layout: "header, reach, diff, flags, tree, footer"
  behavior: default
  require_changes: true
