# codecov.yml (versión con reglas por rama)

coverage:
  status:
    patch:
    
      main:
        target: 80%
        
      develop:
        target: 80%

      default:
        target: off 
        
    project:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false