name: Unit Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-test-build:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 2. Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: 3. Install Dependencies
        run: yarn install

      - name: 4. Run Tests & Generate Coverage Report
        run: yarn test -- --coverage --coverageReporters='lcov' --coverageReporters='json-summary'

      - name: 5. Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
